---
title: "Review indexing"
---

Yesterday we covered 1d and 2d data structures, including indexing. Recall the subgoals for evaluating indexing expressions.

1. Identify the object being indexed (vector, list, matrix, etc)
2. Identify the index (inside [ ] or following $)
3. Determine the type of the index (positive integers, negative integers, conditions, names, blanks) and evaluate it
4. Apply the index to the object and determine the result

We'll review yesterday's content by using these subgoals to understand the following code.

```{r}
set.seed(1)

# Chunk 1
coral_row <- 3
coral_col <- 3
reef <- matrix(0, nrow = 5, ncol = 5)
reef[coral_row, coral_col] <- 1
print("Initial reef")
reef

# Chunk 2
growth_row_lookup <- c(-1, -1, -1, 0, 1, 1, 1, 0)
growth_col_lookup <- c(-1, 0, 1, 1, 1, 0, -1, -1)

# Chunk 3
growth_roll <- sample(1:8, size = 1)
print("Growth direction roll")
growth_roll
growth_row <- coral_row + growth_row_lookup[growth_roll]
growth_col <- coral_col + growth_col_lookup[growth_roll]
reef[growth_row, growth_col] <- 1
print("Updated reef")
reef
```

## Chunk 1

On a sheet of paper

1. Identify the object being indexed (vector, list, matrix, etc)
2. Identify the index (inside [ ] or following $)
3. Determine the type of the index (positive integers, negative integers, conditions, names, blanks) and evaluate it
4. Apply the index to the object and determine the result
