---
title: "Control structures"
subtitle: "Day 3"
description: "Wednesday August 12^th^, 2025"
---



<!-- ## Pre-class prep -->

<!-- No pre-class prep before our first day of class! -->

## Morning session: Conditions and logic

* {{< fa ghost title="A ghost" >}} [Review day 2](slides/day3am-slides.qmd){target="_blank"}
* {{< fa pen-to-square title="A pencil writing on paper" >}} [Code sleuth: conditions and logic](activities/day3/day3am-code-sleuth.pdf){target="_blank"}
* {{< fa users-line title="Multiple people working together" >}} Live coding demo: if-else if-else
* {{< fa diagram-project title="Nodes connected by edges" >}} [Concept mapping: conditions and logic](activities/day3/day3am-concept-mapping.pdf){target="_blank"}
* {{< fa square-check title="A checked checkbox" >}} [Exit ticket](https://forms.gle/BZuu5Ha6PiP38Uo6A){target="_blank"}

## Afternoon session: Loops

* {{< fa pen-to-square title="A pencil writing on paper" >}} [Code sleuth: indexing](activities/day2/day2pm-code-sleuth.pdf){target="_blank"}
* {{< fa users-line title="Multiple people working together" >}} Live coding demo: indexing and 2d data
* {{< fa pen-to-square title="A pencil writing on paper" >}} [SLWE: indexing](activities/day2/day2pm-slwe.pdf){target="_blank"}
* {{< fa laptop title="A laptop" >}} [Debugger: indexing errors](activities/day2/day2pm-debugger.qmd)
* {{< fa diagram-project title="Nodes connected by edges" >}} [Concept mapping: Indexing and 2d data](activities/day2/day2pm-concept-mapping.pdf){target="_blank"}
* {{< fa square-check title="A checked checkbox" >}} [Exit ticket](https://forms.gle/bjpWmE58VB5gnuMr5){target="_blank"}

## End-of-day practice

Complete the following tasks / activities before heading home for the day!

- {{< fa laptop title="A laptop" >}} [**Day 2 Practice:** Initialize the reef](eod/eod-day2.qmd)

